### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by silicahd** [typicms/typicms#213]
I am looking to add two major updates to this script. 

1. Change the design to tailwindcss. 
2. We have made a drag and drop HTML builder that we want to include in the pages module.

**Comment by ivarsmednis** [comment]
Your html builder solution sounds intriguing.  Looking forward to checking it out!

**Comment by sdebacker** [comment]
Any news on this ?

**Comment by silicahd** [comment]
Sorry we never published it because we use a third party. We now use this builder with the TypiCMS https://www.vvveb.com/  i do not like their builder as it is not laravel but you can just use the drag and drop. Alternatively you can use the paid version of https://innovastudio.com/contentbox  we were going to publish with this one but have since moved to the vvveb.
