### ISSUE TITLE
Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by osindex** [TypiCMS/TypiCMS#39]
## Installation:
```php
FatalErrorException in Container.php line 698: 
Maximum function nesting level of '100' reached, aborting!
```
* when i go to http://mywebsite.local/admin and ... print it.
* rebuild but nothing.
* MAMP PHP5.5.26
* thk.

**Comment by sdebacker** [comment]
I don’t know exactly what's wrong, but you can found a lot of info on the web about that Exception, for example here : https://laracasts.com/discuss/channels/general-discussion/l5-maximum-function-nesting-level-of-100-reached-aborting?page=1

**Comment by sdebacker** [comment]
You can try to configure xcode to allow more nesting levels.

**Comment by osindex** [comment]
Yes.
Solution is to add xdebug.max_nesting_level = 200 in my php.ini
Because other L5 are normal, so I did not expect this.
:+1:

**Comment by fstigre** [comment]
Add the following line at the beginning of either the `bootstrap/autoload.php` or  the `public/views/index.php` file.

        `ini_set('xdebug.max_nesting_level', 200);`
