### ISSUE TITLE
vendor/typicms/history/src/repositories

### ISSUE THREAD

**Issue by Nolthar** [TypiCMS/TypiCMS#40]
EloquentHistory
CacheDecorator
HistoryInterface

has colliding function name empty() 

this resulting in:

syntax error, unexpected 'empty' (T_EMPTY), expecting identifier (T_STRING)

on PHP 5.6.14

Changing name to f.e. clear() seems to be good workaround and quick fix, but need another steps to bring back history clear function online.

**Comment by sdebacker** [comment]
You are right, but If you run composer update, it is already corrected. Am I wrong?
