### ISSUE TITLE
i have some problem

### ISSUE THREAD

**Issue by SaifulAzam** [TypiCMS/TypiCMS#41]
I try to install Modules. Everything was successfully installed and i see the Module names in the admin nav but when i click the Module its 404 error. 
Can you tell me what missed it?

**Comment by sdebacker** [comment]
The module provider is probably set at the wrong place in **config/app.php**.
You should set it before Core Module Provider, just below:

        /*
         * TypiCMS Modules Service Providers...
         */
        TypiCMS\Modules\Translations\Providers\TranslationServiceProvider::class,

**Comment by SaifulAzam** [comment]
Thank you
