### ISSUE TITLE
API Endpoints not respecting public setting.

### ISSUE THREAD

**Issue by eahrold** [TypiCMS/TypiCMS#44]
I'm trying to get TypiCMS configured and even after granting access to the "Public" group in the dashboard, the api endpoints return 401 error until I actually log in.

Where it seems to be getting hung up is the [app/HTTP/Middleware/Authenticate L19-29](https://github.com/TypiCMS/TypiCMS/blob/master/app/Http/Middleware/Authenticate.php#L19-L29)

The call is getting passed through this no matter the settings, however if I disable this, then the dashboard doesn't redirect correctly.

Any advice.

Thanks.

**Comment by sdebacker** [comment]
Actually the public group does nothing, it's present only as an example. As it add confusion, I will remove it from groupSeeder.
For your access problem, did you try to check "superuser" in the user form ?

**Comment by eahrold** [comment]
I'm not sure exactly what you mean here, but currently there is only one user, and that user is the super user.

Is there suppose to be a "Guest" user, because I don't have one listed and that may be the issue.

**Comment by sdebacker** [comment]
No need of a guest user. What are the api calls that gives you problems ?

**Comment by eahrold** [comment]
I've scaffolded a new module
```
php artisan typicms:create cats
```
and then when I do a call to 

```
http://mydev.dev/api/cats
```
if made from ajax I get a 401,
if tried using a browser I get redirected to /login

However, once I actually do login to the dashboard, the same call succeeds.

**Comment by sdebacker** [comment]
In TypiCMS, the API is only used by angular in admin side, so API calls require to be authenticated and having the correct rights.

What you can do is publishing the core module (```php artisan typicms:publish core```) then in ```TypiCMS\Modules\Core\Http\Controllers\BaseApiController``` replace ```$this->middleware('api');``` by ```$this->middleware('api', ['except' => ['index']]);``` in order to allow everybody to access http://mydev.dev/api/cats

Does it help you?

**Comment by eahrold** [comment]
Yeah, that'll solve it. 
I'm always just a bit reluctant to publish the core of a framework, I don't want to miss out on improvements.  

Just spitballing, It'd be nice to be able to configure that in the Modules themselves. something like 
```php
protected $publicPaths = ['index', 'show'];
```

Then setting up the middleware in the core like this...
```php
protected $publicPaths = [];

public function __construct($repository = null)
{
    $this->middleware('api', ['except' => $publicPath]);`
    $this->repository = $repository;
}
```

**Comment by sdebacker** [comment]
Nice, I'm open for the PR.
